# Generated by Django 3.0.3 on 2020-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='min_price',
            field=models.IntegerField(default=0),
        ),
    ]
