# Generated by Django 3.0.3 on 2020-02-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200224_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='category',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='search',
            name='city',
            field=models.CharField(default='', max_length=400),
        ),
    ]
