# Generated by Django 3.0.3 on 2020-02-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200224_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='max_price',
            field=models.IntegerField(null=True),
        ),
    ]
