# Generated by Django 3.0.3 on 2020-02-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200224_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='max_price',
            field=models.IntegerField(default=99999999999),
        ),
    ]
