# Generated by Django 3.0.3 on 2020-02-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200224_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='category',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='search',
            name='city',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='search',
            name='max_price',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='search',
            name='min_price',
            field=models.CharField(max_length=400),
        ),
    ]
